# Generated by Django 4.1.1 on 2023-03-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0001_initial"),
    ]

    operations = []
