# Generated by Django 4.1.1 on 2023-03-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0002_auto_20230312_1447"),
    ]

    operations = []
